apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:1j0TxE7qOvGRPFU6x8kHDqXLW2MAlJ2trr5CjaJRKIs0G9bYBcPB9RArnpbf1F9c+bA7bK27S6RPAqvZPMxDR8lR3JjnvFrV6YDa8xrej2/ER6va0m/dJ1D2dRXKYA==,iv:VS7nPeW0Vr2H9QEO0OLYSCEzkuYBREGeppC/J7npEjI=,tag:k6YWYbUg+jYIEFkWG2q5sQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:D45rVdOOrK6r6p4uNg==,iv:XnSNNo7/d9FyBsgiJ+USsQSG42jxzS4cODgDWqW6PrU=,tag:uEQTwhnyOvUv6+AB+iHnKA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:hbZWHOFHZHgtHF9BuyQBOwCRhsso,iv:IuQVHK/WoANw+fkFNEu8enQ+f5u8nGIajXz4zL5Sk/4=,tag:Zmv1nAp8+1wPSDw7BB/iOA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:iCH/PYokN7kXJldITI/ti6g7J2ompMnuMHivouNwV5FvTirO,iv:rlzu5FnkdytTrkCvS8YSnhWLQF+94miZEE88YlkIfEE=,tag:t4buLS7OlHPXB7fGr0tLeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uu6l38vuhpts52zm7vncjtcr34cg2nqqeyree7qvl59jlfez55asjm64pm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYklZT25XcWZxb3cxK0Rl
            bytndzlvNWpnQkVvU1YrMUdkOE9GdkhMbkRRCmhOeHNWK1Q3NHZtY0tURGxJcmNH
            SFNHcy9tKzR3VHlhTnRGTUlmanY2cjgKLS0tIEFrRHZoVlpuV2RydGpHdGxzYU1P
            UFkwek0wc1B3OXpwZ3VXYUl6eEgwK0EKeN/jB+kyMXwH7DBuyZVFlyleN7FyaRUz
            4lcfwUbkp7Lhfb+HHpDC0QcgW7I5P5TlYR36l9R28nL0lgQQk2M/mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T08:45:47Z"
    mac: ENC[AES256_GCM,data:EjdPub+3m8DHDDep7Ms4Fve4nAryov8UrCTl/1CA4f2p7piS5uIM0sbOn1/AywtL1cXY0In8lWjOq5IRxxZZDiVnLkTyNgjoJvgRmtvflW+GHCQVnek8c2xPRAfgE4066oxk7uNw9haWMvIZW6ZtMPeCb7INvIbbW095mqgwo6I=,iv:cXzK9gKSvQbtgqyynUVrVqFbiytUrjnJ5zna30zIwvE=,tag:h4NWoECp71VH6j1w9nGqNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
