apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:5sr6GcF2ezUdPP2/i9/oyN42gOe+V+PvLFt0qJ5n0uI=,iv:2sqpSHA3xMBQUh0kl9KQTDFyB3hihwoKaZhnL3dz0b8=,tag:90oWn5b7zGPJcsJLhBm85w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uu6l38vuhpts52zm7vncjtcr34cg2nqqeyree7qvl59jlfez55asjm64pm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxR2F2c0QrU000c1FBYzV1
            Tkt3NS9vQzFDV1BxMFV4MWxUZDl6Y2NYL3kwCnlXdXVaeWc5OFhYSkgwMkMzekNF
            MVJKT0FzdS9MVEdJRWtBd2t4QTV6dTQKLS0tICt4cjRTUm0yc0s0SjJJU1B2OGNl
            czhBMzNRVytXVWRBTEI5UzNId0tkK2MKwoyogoI66wK30cgJV20QWbsEB2x3uFt+
            pn7cddkefx1GkL4gmGVbkuw6MJ111/2TOifo/GZKy/2eZa0bpPwnmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-02T15:47:51Z"
    mac: ENC[AES256_GCM,data:f+kq8StMudvPbYGu/JBfuLZwICHPRQzN537LLbubOo8XxzVmYV7fMXIJ6ZBUtihjCHsy+GxOo4NYUopPzgxGxOQeu1qzGsp6F/0EFA6t5sUp7ap2ve1KdKv7Beb4Qtz5UhOmPP9TVV7oMRrHUFf7dO17YdAIfya6HdT5o+1ya2Q=,iv:pLS66vFi/pRnrkM7dNzoUMMdTyaTDMUei1YIvPR/STs=,tag:gnKEti/um8B/WdI1Z6+8Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
